### ISSUE TITLE
SDP option to use blas-sys and lapack-sys

### ISSUE THREAD

**Issue by jwnimmer-tri** [oxfordcontrol/Clarabel.rs#61]
Here's a feature request ...

**Is your feature request related to a problem? Please describe.**

In https://github.com/RobotLocomotion/drake/issues/19449, I'm working to add Clarabel integration into Drake.  Most users of Drake use our pre-compiled binary releases (e.g., from PyPI) instead of building from source.

As such, it is not practical for us to force a choice of BLAS/LAPACK at compile time.  Instead, we dynamically link to the `libblas.so` and `libpack.so` (`libblas.dylib` and `liblapack.dylib`) from the user's operating system, so that their choice of the best BLAS for their own computer applications is respected.  It allows us to ship one binary release of Drake that can perform well on many different computers.

At the moment, it does not appear that `Clarabel.rs` or `Clarabel.cpp` offer a feature to use the system BLAS, which prevents us from extending our BLAS convention to Clarabel as well.

**Describe the solution you'd like**

See https://github.com/blas-lapack-rs/blas-lapack-rs.github.io/wiki for background.

The `Cargo.toml` as of 0.6.0 currently offers these features:

```toml
# enables blas/lapack for SDP support, with blas/lapack src unspecified
sdp = ["blas","lapack"]

# explicit configuration options for different blas flavours
sdp-accelerate = ["sdp", "blas-src/accelerate", "lapack-src/accelerate"]
sdp-netlib     = ["sdp", "blas-src/netlib", "lapack-src/netlib"]
sdp-openblas   = ["sdp", "blas-src/openblas", "lapack-src/openblas"]
sdp-mkl        = ["sdp", "blas-src/intel-mkl", "lapack-src/intel-mkl"]
sdp-r          = ["sdp", "blas-src/r", "lapack-src/r"]
```

I'd like to request a feature option to use the system blas, something like:

```toml
sdp-sys        = ["sdp", "blas-sys", "lapack-sys"]
```

I believe it also might require changes to `src/algebra/dense/blas.rs` etc to spell things a little differently.

**Describe alternatives you've considered**

I've been trying to prepare my own patches to accomplish this, but doing it with downstream patching it fairly awkward, and my unfamiliarity with Rust is slowing me down a bit.  Since I would plan to upstream the patches anyway, I thought I'd ask here to see if we we could find a way to ship 0.7.0 with `blas-sys` out of the box.  Y'all might be able to do this more quickly than myself.
